[package]
name = "derives"
version = "0.1.0"
authors = ["Atkins <atkinschang@gmail.com>"]
edition = "2018"

[dependencies]
proc-macro-error = "0.4"
proc-macro2 = "1.0"
quote = "1.0"
syn = "1.0"
synstructure = "0.12"

[lib]
proc-macro = true

[features]
default = ["std"]

std = []
unstable = []

