newline_style = "Unix"
use_small_heuristics = "Max"
reorder_impl_items = true
use_field_init_shorthand = true
use_try_shorthand = true

unstable_features = true
condense_wildcard_suffixes = true
fn_single_line = true
format_strings = true
format_macro_matchers = true
imports_layout = "HorizontalVertical"
merge_imports = true
normalize_comments = true
report_todo = "Always"
report_fixme = "Always"
format_code_in_doc_comments = true
wrap_comments = true
version = "Two"
normalize_doc_attributes = true
